CREATE TYPE workout AS ENUM
('Date','Exercise Name', 'Set','Weight','Notes')

CREATE TABLE workouts
(
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  exercise_name TEXT NOT NULL,
  workout_set INTEGER NOT NULL,
  workout_weight INTEGER NOT NULL,
  user_id INTEGER REFERENCES fitpad_users(id) ON DELETE CASCADE NOT NULL,
  notes TEXT
);